flash-mode 2 configures grub and efi when included in MACHINE_FEATURES flash-mode 1 configures grub when included in MACHINE_FEATURES
(eg500 device boots successfully from nvme after flash-mode 2 run)

Signed-off-by: Marcel Lilienthal <134974+mlilien@users.noreply.github.com>

diff --git a/recipes-omnect/initrdscripts/omnect-os-initramfs/flash-mode b/recipes-omnect/initrdscripts/omnect-os-initramfs/flash-mode
--- a/recipes-omnect/initrdscripts/omnect-os-initramfs/flash-mode
+++ b/recipes-omnect/initrdscripts/omnect-os-initramfs/flash-mode
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 #
 # optionally provide flashing whole disk image in INITRAMFS context
@@ -128,6 +128,8 @@ run_bmap_tool() {
 
 # deploy WIC image via network to (same) active block device
 run_flash_mode_1() {
+    local root_a_p=""
+    local machine_features=""
     msg "Entering omnect flashing mode 1 ..."
 
     # disable flash mode for subsequent restarts
@@ -141,17 +143,18 @@ run_flash_mode_1() {
     setup_network ${OMNECT_FLASH_MODE_ETH} || return
     run_bmap_tool || return
 
-    sync
-
-    if [ -f /etc/omnect/grub.cfg.in ]; then
+    machine_features=$(grep ^MACHINE_FEATURES= /etc/os-release | awk -F'"' '{print $2}')
+    if [[ " ${machine_features} " =~ " grub " ]]; then
         mkdir -p /tmp/boot
         mount /dev/omnect/boot /tmp/boot
-        rootblk=$(readlink -f /dev/omnect/rootblk)
-        sed "s#@@ROOT_DEVICE@@#${rootblk}#g" /etc/omnect/grub.cfg.in > /tmp/boot/grub.cfg
+        root_a_p=$(readlink -f /dev/omnect/rootA)
+        root_a_p=${root_a_p::-1}
+        sed "s#@@ROOT_DEVICE@@#${root_a_p}#g" /etc/omnect/grub.cfg.in > /tmp/boot/EFI/BOOT/grub.cfg
         umount /tmp/boot
     fi
 
     msg "Rebooting system..."
+    sync
     reboot -f
     # -- never reached --
 }
@@ -171,14 +174,15 @@ run_flash_mode_2() {
     local data_partition=""
     local data_partition_size=""
     local data_partition_start=""
+    local efi_entries=""
     local extended_partition=""
     local extended_partition_size=""
     local extended_partition_start=""
     local last_lba=""
+    local machine_features=""
     local p=""
     local part_type=""
     local rootfs_bootpart=""
-
 
     echo "Entering omnect flashing mode 2 ..."
 
@@ -322,16 +326,33 @@ run_flash_mode_2() {
     run_cmd_stdout dd if=/tmp/uboot_env_ff.img of="${blk_dev_dst}" oflag=seek_bytes seek=$((OMNECT_FLASH_MODE_UBOOT_ENV1_START*1024)) || return 1
     run_cmd_stdout dd if=/tmp/uboot_env_ff.img of="${blk_dev_dst}" oflag=seek_bytes seek=$((OMNECT_FLASH_MODE_UBOOT_ENV2_START*1024)) || return 1
 
-    run_cmd_stdout sync
-
-    if [ -f /etc/omnect/grub.cfg.in ]; then
+    machine_features=$(grep ^MACHINE_FEATURES= /etc/os-release | awk -F'"' '{print $2}')
+    if [[ " ${machine_features} " =~ " grub " ]]; then
+        echo "Configuring grub"
         mkdir -p /tmp/boot
         mount ${blk_dev_dst}${p}1 /tmp/boot
-        sed "s#@@ROOT_DEVICE@@#${blk_dev_dst}#g" /etc/omnect/grub.cfg.in > /tmp/boot/grub.cfg
+        sed "s#@@ROOT_DEVICE@@#${blk_dev_dst}${p}#g" /etc/omnect/grub.cfg.in > /tmp/boot/EFI/BOOT/grub.cfg
         umount /tmp/boot
+    else
+        echo "REMOVE ME grub.cfg.in expected but not found"
+        run_cmd_stdout ls -l /etc/omnect
+    fi
+
+
+    if [[ " ${machine_features} " =~ " efi " ]]; then
+        echo "Configuring efi"
+        run_cmd_stdout efibootmgr --create --disk ${blk_dev_dst} --part 1 --label "omnect os" --loader \\\\EFI\\\\BOOT\\\\bootx64.efi || return 1
+        # delete all efi entries but last
+        efi_entries=$(efibootmgr | grep ^Boot[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]\* | awk '{print $1}'| sed  '$ d')
+        for i in ${efi_entries}; do
+            i=${i#Boot}
+            i=${i%\*}
+            run_cmd_stdout efibootmgr --bootnum ${i} --delete-bootnum || return 1
+        done
     fi
 
     echo "flash mode 2 successfully finished"
+    run_cmd_stdout sync
     return 0
 }
 
